### ISSUE TITLE
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt-vue-multiselect')  

### ISSUE THREAD

**Issue by imikay** [spektrummedia/nuxt-vue-multiselect#6]
nuxt version 3.2.3, when adding module in nuxt.config.js
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt-vue-multiselect')

**Comment by imikay** [comment]
I choose to use vue-multiselect directly, you can use vue-multiselect just fine in nuxt 3. No integration config need, and no bug. Bye.

**Comment by cpiautoltd** [comment]
@imikay How did you use vue-multiselect directly? Could you please elaborate?

**Comment by aleksejantipov** [comment]
> I choose to use vue-multiselect directly, you can use vue-multiselect just fine in nuxt 3. No integration config need, and no bug. Bye.

Can you tell me more?

**Comment by diemuzi** [comment]
This is the output when installing this module.

npm i nuxt-vue-multiselect

npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

After adding nuxt-vue-multiselect to the Nuxt modules and starting the project this happens.

 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt-vue-multiselect')                                                                                                                        3:31:33 PM  

  at module.exports (node_modules\nuxt-vue-multiselect\lib\module.js:6:20)
  at installModule (/C:/Users/diemu/PycharmProjects/gwhcp/gui/node_modules/@nuxt/kit/dist/index.mjs:2409:101)
  at async initNuxt (/C:/Users/diemu/PycharmProjects/gwhcp/gui/node_modules/nuxt/dist/index.mjs:3238:7)
  at async load (/C:/Users/diemu/PycharmProjects/gwhcp/gui/node_modules/nuxi/dist/chunks/dev.mjs:205:9)
  at async Object.invoke (/C:/Users/diemu/PycharmProjects/gwhcp/gui/node_modules/nuxi/dist/chunks/dev.mjs:249:5)
  at async _main (/C:/Users/diemu/PycharmProjects/gwhcp/gui/node_modules/nuxi/dist/cli.mjs:49:20)

**Comment by samueltomaselli** [comment]
Did anyone fix this?

**Comment by idolpx** [comment]
I'd like to try this too if it gets fixed.
